import xml.etree.ElementTree as ET
import xml.dom.minidom
from pathlib import Path
from vibmo.core.schema import VibmoProject, LayerType

class Fcp7Exporter:
    """
    Exports a VibmoProject to the Final Cut Pro 7 XML Interchange Format (.xml).
    This allows timelines generated by Vibmo's AI to be natively opened in 
    Adobe Premiere Pro and DaVinci Resolve.
    """
    
    @classmethod
    def export(cls, project: VibmoProject, output_path: str, project_name: str = "Vibmo Sequence") -> None:
        fps = project.fps
        
        # Root element
        xmeml = ET.Element("xmeml", version="5")
        
        # Sequence
        sequence = ET.SubElement(xmeml, "sequence")
        ET.SubElement(sequence, "name").text = project_name
        ET.SubElement(sequence, "duration").text = str(int(project.duration * fps))
        
        rate = ET.SubElement(sequence, "rate")
        ET.SubElement(rate, "timebase").text = str(fps)
        ET.SubElement(rate, "ntsc").text = "FALSE"
        
        media = ET.SubElement(sequence, "media")
        video = ET.SubElement(media, "video")
        
        # Format properties
        vformat = ET.SubElement(video, "format")
        vschar = ET.SubElement(vformat, "samplecharacteristics")
        ET.SubElement(vschar, "width").text = str(project.width)
        ET.SubElement(vschar, "height").text = str(project.height)
        ET.SubElement(vschar, "pixelaspectratio").text = "square"
        
        format_rate = ET.SubElement(vschar, "rate")
        ET.SubElement(format_rate, "timebase").text = str(fps)
        ET.SubElement(format_rate, "ntsc").text = "FALSE"
        
        # Process tracks
        clip_id_counter = 1
        file_id_counter = 1
        
        for track_data in project.tracks:
            track = ET.SubElement(video, "track")
            for shot in track_data.shots:
                for layer in shot.layers:
                    if layer.type not in [LayerType.VIDEO, LayerType.IMAGE]:
                        continue # FCP XML mainly targets media files.
                        
                    clipitem = ET.SubElement(track, "clipitem", id=f"clipitem-{clip_id_counter}")
                    ET.SubElement(clipitem, "name").text = layer.name
                    ET.SubElement(clipitem, "enabled").text = "TRUE"
                    
                    # Convert seconds to frames
                    start_frame = int(shot.start_time * fps)
                    end_frame = int((shot.start_time + shot.duration) * fps)
                    
                    ET.SubElement(clipitem, "start").text = str(start_frame)
                    ET.SubElement(clipitem, "end").text = str(end_frame)
                    
                    # In and out points (assume whole file for now)
                    ET.SubElement(clipitem, "in").text = "0"
                    ET.SubElement(clipitem, "out").text = str(end_frame - start_frame)
                    
                    # File reference
                    file_path = layer.properties.get("image_path", layer.properties.get("video_path", ""))
                    if file_path:
                        file_el = ET.SubElement(clipitem, "file", id=f"file-{file_id_counter}")
                        ET.SubElement(file_el, "name").text = Path(file_path).name
                        ET.SubElement(file_el, "pathurl").text = f"file://localhost/{Path(file_path).absolute().as_posix()}"
                        
                        file_rate = ET.SubElement(file_el, "rate")
                        ET.SubElement(file_rate, "timebase").text = str(fps)
                        ET.SubElement(file_rate, "ntsc").text = "FALSE"
                        
                        media_el = ET.SubElement(file_el, "media")
                        vid_el = ET.SubElement(media_el, "video")
                        file_id_counter += 1
                        
                    clip_id_counter += 1
                    
        # Write to file
        xmlstr = xml.dom.minidom.parseString(ET.tostring(xmeml)).toprettyxml(indent="  ")
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(xmlstr)
