"""
Multi-scene composition, sequencing, and visual transitions.
"""

from vibmo.composition.composition import Composition, Shot
from vibmo.composition.sequence import Sequence, Transition, CrossFade, Slide as SequenceSlide
from vibmo.composition.transitions import (
    CrossDissolve,
    WhipPan,
    ZoomPunch,
    GlitchTransition,
    LightLeak,
    ShapeWipe,
    DipToColor,
)
from vibmo.composition.transitions_expanded import (
    Slide as AdvancedSlide,
    PushCut,
    Fade,
    Dissolve,
    Iris,
    Wipe,
    ZoomBlur,
    Ripple,
    Flip,
    BookFlip,
    SlideDirection,
    IrisShape,
    WipeDirection,
    FlipDirection,
    BookFlipDirection,
    slide,
    push_cut,
    fade,
    dissolve,
    iris,
    wipe,
    zoom_blur,
    ripple,
    flip,
    book_flip,
)
from vibmo.composition.webgl_transitions import (
    WebGL2TransitionEngine,
    ShaderTransition,
    create_transition_engine,
)
from vibmo.composition.timing import (
    TimingConfig,
    SpringConfig,
    TimingFunction,
    LinearTiming,
    SpringTiming,
    CubicBezierTiming,
    EaseInTiming,
    EaseOutTiming,
    EaseInOutTiming,
    EasingTiming,
    linear_timing,
    spring_timing,
    cubic_bezier_timing,
    ease_in_timing,
    ease_out_timing,
    ease_in_out_timing,
    easing_timing,
    TIMING_PRESETS,
    get_timing_preset,
    calculate_progress,
    interpolate_value,
    interpolate_position,
    interpolate_color,
    AnimationTimeline,
)

# Use enhanced slide as default Slide
Slide = AdvancedSlide

__all__ = [
    "Composition",
    "Shot",
    "Sequence",
    "Transition",
    "CrossFade",
    "Slide",  # Enhanced version from transitions_expanded
    "SequenceSlide",  # Original slide from sequence.py for backward compatibility
    "CrossDissolve",
    "WhipPan",
    "ZoomPunch",
    "GlitchTransition",
    "LightLeak",
    "ShapeWipe",
    "DipToColor",
    # New transitions
    "PushCut",
    "Fade",
    "Dissolve",
    "Iris",
    "Wipe",
    "ZoomBlur",
    "Ripple",
    "Flip",
    "BookFlip",
    # Transition enums
    "SlideDirection",
    "IrisShape",
    "WipeDirection",
    "FlipDirection",
    "BookFlipDirection",
    # Convenience functions
    "slide",
    "push_cut",
    "fade",
    "dissolve",
    "iris",
    "wipe",
    "zoom_blur",
    "ripple",
    "flip",
    "book_flip",
    # WebGL transition engine
    "WebGL2TransitionEngine",
    "ShaderTransition",
    "create_transition_engine",
    # Timing system
    "TimingConfig",
    "SpringConfig",
    "TimingFunction",
    "LinearTiming",
    "SpringTiming",
    "CubicBezierTiming",
    "EaseInTiming",
    "EaseOutTiming",
    "EaseInOutTiming",
    "EasingTiming",
    "linear_timing",
    "spring_timing",
    "cubic_bezier_timing",
    "ease_in_timing",
    "ease_out_timing",
    "ease_in_out_timing",
    "easing_timing",
    "TIMING_PRESETS",
    "get_timing_preset",
    "calculate_progress",
    "interpolate_value",
    "interpolate_position",
    "interpolate_color",
    "AnimationTimeline",
]

